version: "3.9"

services:

  url-shortener-ui:
    image: dbetta/urlshortener-ui
    ports:
      - "10000:80"
    restart: always
    depends_on:
      - urlshortener-api

  urlshortener-api:
    image: dbetta/urlshortener-be
    environment:
      - DB_HOST=url-shortener-database
      - DB_PORT=5432
    restart: always
    depends_on:
      - url-shortener-database


  # postgres database
  url-shortener-database:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=url_shortener
      - POSTGRES_PASSWORD=s3cr3t

volumes:
  postgres:


